# Generated by Django 5.0.3 on 2024-04-02 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grrabasite', '0002_alter_user_music_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='music_style',
            field=models.CharField(blank=True, choices=[('blues', 'Блюз'), ('latin', 'Латиноамериканская музыка'), ('rnb', 'Ритм-н-блюз'), ('jazz', 'Джаз'), ('chanson', 'Шансон, романс, авторская песня'), ('rap', 'репер'), ('folk', 'Фолк-музыка'), ('electronic', 'Электронная музыка'), ('country', 'Кантри')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music', to='grrabasite.musiccategory'),
        ),
    ]
