# Generated by Django 5.0.3 on 2024-04-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grrabasite', '0004_like_is_like_alter_user_music_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_like',
        ),
        migrations.AlterField(
            model_name='user',
            name='music_style',
            field=models.CharField(blank=True, choices=[('rnb', 'Ритм-н-блюз'), ('blues', 'Блюз'), ('jazz', 'Джаз'), ('chanson', 'Шансон, романс, авторская песня'), ('electronic', 'Электронная музыка'), ('country', 'Кантри'), ('folk', 'Фолк-музыка'), ('latin', 'Латиноамериканская музыка'), ('rap', 'репер')], max_length=50, null=True),
        ),
    ]
