# Generated by Django 5.0.3 on 2024-04-14 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grrabasite', '0005_remove_like_is_like_alter_user_music_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='music_style',
            field=models.CharField(blank=True, choices=[('rnb', 'Ритм-н-блюз'), ('blues', 'Блюз'), ('electronic', 'Электронная музыка'), ('folk', 'Фолк-музыка'), ('latin', 'Латиноамериканская музыка'), ('rap', 'репер'), ('country', 'Кантри'), ('chanson', 'Шансон, романс, авторская песня'), ('jazz', 'Джаз')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OtzuvUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otzuv', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otzuv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
