# Generated by Django 5.0.3 on 2024-04-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grrabasite', '0006_alter_user_music_style_otzuvuserprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtzuvUserProfile',
            new_name='OtzuvUserMusic',
        ),
        migrations.AlterField(
            model_name='user',
            name='music_style',
            field=models.CharField(blank=True, choices=[('rap', 'репер'), ('electronic', 'Электронная музыка'), ('chanson', 'Шансон, романс, авторская песня'), ('latin', 'Латиноамериканская музыка'), ('folk', 'Фолк-музыка'), ('country', 'Кантри'), ('jazz', 'Джаз'), ('rnb', 'Ритм-н-блюз'), ('blues', 'Блюз')], max_length=50, null=True),
        ),
    ]
