# Generated by Django 5.0.3 on 2024-04-14 21:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grrabasite', '0007_rename_otzuvuserprofile_otzuvusermusic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='music_style',
            field=models.CharField(blank=True, choices=[('latin', 'Латиноамериканская музыка'), ('country', 'Кантри'), ('folk', 'Фолк-музыка'), ('electronic', 'Электронная музыка'), ('chanson', 'Шансон, романс, авторская песня'), ('rap', 'репер'), ('blues', 'Блюз'), ('rnb', 'Ритм-н-блюз'), ('jazz', 'Джаз')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='grrabasite.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OtzuvUserMusic',
        ),
    ]
