# Generated by Django 5.0.3 on 2024-04-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grrabasite', '0008_alter_user_music_style_review_delete_otzuvusermusic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='music_style',
            field=models.CharField(blank=True, choices=[('jazz', 'Джаз'), ('rnb', 'Ритм-н-блюз'), ('electronic', 'Электронная музыка'), ('country', 'Кантри'), ('folk', 'Фолк-музыка'), ('chanson', 'Шансон, романс, авторская песня'), ('blues', 'Блюз'), ('rap', 'репер'), ('latin', 'Латиноамериканская музыка')], max_length=50, null=True),
        ),
    ]
