# Generated by Django 5.0.3 on 2024-04-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grrabasite', '0009_alter_user_music_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='music_style',
            field=models.CharField(blank=True, choices=[('rnb', 'Ритм-н-блюз'), ('latin', 'Латиноамериканская музыка'), ('electronic', 'Электронная музыка'), ('chanson', 'Шансон, романс, авторская песня'), ('jazz', 'Джаз'), ('country', 'Кантри'), ('rap', 'репер'), ('blues', 'Блюз'), ('folk', 'Фолк-музыка')], max_length=50, null=True),
        ),
    ]
