# Generated by Django 5.0.3 on 2024-04-14 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grrabasite', '0010_alter_user_music_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='music_style',
            field=models.CharField(blank=True, choices=[('jazz', 'Джаз'), ('rnb', 'Ритм-н-блюз'), ('electronic', 'Электронная музыка'), ('rap', 'репер'), ('country', 'Кантри'), ('chanson', 'Шансон, романс, авторская песня'), ('blues', 'Блюз'), ('latin', 'Латиноамериканская музыка'), ('folk', 'Фолк-музыка')], max_length=50, null=True),
        ),
    ]
